In [1]:
import numpy as np

In [2]:
a=np.random.randint(1,100,10)
a

array([ 3, 96, 94, 75, 83, 91,  4, 53, 26,  5])

In [ ]:
# sort() method use the sort data

In [4]:
np.sort(a)

array([ 3,  4,  5, 26, 53, 75, 83, 91, 94, 96])

In [5]:
# reverse

np.sort(a)[::-1]

array([96, 94, 91, 83, 75, 53, 26,  5,  4,  3])

In [11]:
b=np.random.randint(1,100,24).reshape(6,4)
b

array([[96, 12, 46, 45],
       [27, 92, 33, 28],
       [14, 34, 86, 70],
       [12, 14, 77, 30],
       [81, 33, 75, 80],
       [31, 44, 58, 21]])

In [12]:
np.sort(b)

array([[12, 45, 46, 96],
       [27, 28, 33, 92],
       [14, 34, 70, 86],
       [12, 14, 30, 77],
       [33, 75, 80, 81],
       [21, 31, 44, 58]])

In [13]:
# append() method use 


In [14]:
np.append(a,100)

array([  3,  96,  94,  75,  83,  91,   4,  53,  26,   5, 100])

In [15]:
np.append(b,200)

array([ 96,  12,  46,  45,  27,  92,  33,  28,  14,  34,  86,  70,  12,
        14,  77,  30,  81,  33,  75,  80,  31,  44,  58,  21, 200])

In [16]:
np.append(b,np.ones((b.shape[0],1)))

array([96., 12., 46., 45., 27., 92., 33., 28., 14., 34., 86., 70., 12.,
       14., 77., 30., 81., 33., 75., 80., 31., 44., 58., 21.,  1.,  1.,
        1.,  1.,  1.,  1.])

In [ ]:
## np.concatenate((para))

In [21]:
c=np.arange(6).reshape(2,3)
d=np.arange(6,12).reshape(2,3)
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [22]:
# np.unique()

e=np.array([1,1,2,3,4,56,7,7,8])
np.unique(e)

array([ 1,  2,  3,  4,  7,  8, 56])

In [25]:
# np.expand_dims() convert a 2 dimensional array
np.expand_dims(a,axis=0)

array([[ 3, 96, 94, 75, 83, 91,  4, 53, 26,  5]])

In [26]:
# np.where() return the indicate element input array given condtition
# np.where() return the first element if condition is true, otherwise return the second element

a

array([ 3, 96, 94, 75, 83, 91,  4, 53, 26,  5])

In [ ]:
# find all index poostion with value grater than 50
np.where(a>50)

(array([1, 2, 3, 4, 5, 7], dtype=int64),)

In [ ]:
# replace all values > 50 with 0
# syntax : np.where(cond,true,varible)

np.where(a>50,0,a)

array([ 3,  0,  0,  0,  0,  0,  4,  0, 26,  5])

In [29]:
# even no 
np.where(a%2==0,0,a)

array([ 3,  0,  0, 75, 83, 91,  0, 53,  0,  5])

In [30]:
# np.argmax()  bigest number find the index
np.argmax(a)

1

In [31]:
np.argmin(a)

0

In [32]:
# np.cumsum() : use the sum of elements
np.cumsum(a)

array([  3,  99, 193, 268, 351, 442, 446, 499, 525, 530])

In [34]:
# 2d array
np.cumsum(b)

array([  96,  108,  154,  199,  226,  318,  351,  379,  393,  427,  513,
        583,  595,  609,  686,  716,  797,  830,  905,  985, 1016, 1060,
       1118, 1139])

In [35]:
# np.cumprod(): use multiple
np.cumprod(a)

array([          3,         288,       27072,     2030400,   168523200,
       -1844257984,  1212902656,  -140668672,   637581824, -1107058176])

In [ ]:
# np.percentile() : use the percentile of given data

np.percentile(a,100) # highest

96.0

In [ ]:
np.percentile(a,50) # middle

64.0

In [ ]:
np.percentile(a,0) # first

3.0

In [40]:
#np.histogram(): use the frequency count of the given range
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([3, 0, 1, 0, 0, 1, 0, 1, 1, 3], dtype=int64),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [41]:
# np.corrcoef() : use the return person product mpmevent coeficients
# correlaction[-1,1]

salary=np.array([20000,40000,50000,60000])
exp=np.array([1,2,3,4])
np.corrcoef(salary,exp)

array([[1.        , 0.98270763],
       [0.98270763, 1.        ]])

In [42]:
# np.isin() : check the different array of same elements
a

array([ 3, 96, 94, 75, 83, 91,  4, 53, 26,  5])

In [43]:
item=[10,20,30,40,50,60,70,90,100]
np.isin(a,item)

array([False, False, False, False, False, False, False, False, False,
       False])

In [44]:
# np.filp() : reverse of array
np.flip(a)

array([ 5, 26, 53,  4, 91, 83, 75, 94, 96,  3])

In [45]:
# np.put(): change the element of array
np.put(a,[0,1],[110,530]) # (a[index],[number])

In [46]:
a

array([110, 530,  94,  75,  83,  91,   4,  53,  26,   5])