In [1]:
# createing a numpy
import numpy as np 
a=np.array([1,2,3,4,5]) # output vector from 
a

array([1, 2, 3, 4, 5])

In [2]:
# check a type() of array
type(a)

numpy.ndarray

In [3]:
# 2d array
b=np.array([[1,2,3],[4,5,6]])
print(b)  # Output: matrix from

[[1 2 3]
 [4 5 6]]


In [4]:
# 3d array
c=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(c)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [5]:
# 3d array example
d=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(d) # output i: tenser

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [6]:
# dtype : use the change the data type
e=np.array([1,2,3],dtype=float)
e

array([1., 2., 3.])

In [7]:
# np.arange() : range of the number
# synatx: start,stop,step
f=np.arange(1,11)
f

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
# use the [star, stop ,step]
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [9]:
# with reshape():use the shape of array row and column
np.arange(1,13).reshape(3,4) # 3 row and 4 columns

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [10]:
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [11]:
# np.ones((providing the touple)): use for the value intization
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
# np.zeros((providing the touple)): use for the value intization
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
# np.random.random((providing the touple)): use for the value intization
np.random.random((3,4))

array([[0.23759971, 0.11540079, 0.0811457 , 0.63355686],
       [0.52664954, 0.49295667, 0.70759429, 0.46737348],
       [0.5803169 , 0.30178171, 0.97747205, 0.7862806 ]])

In [14]:
# np.linspace() : lineary seprate point
# syntax:[lower-num,upper-num,num-item]
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [15]:
# np.identity : is a diogonal matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
## numpy Attributes ##

In [17]:
a=np.arange(10)
b=np.arange(12,dtype=float).reshape(3,4)
c=np.arange(8).reshape(2,2,2)

In [18]:
#ndim : number of dimesinal
# check a dimesional array
a.ndim

1

In [19]:
b.ndim

2

In [20]:
c.ndim

3

In [21]:
# shape : check a row and columns of array
a.shape

(10,)

In [22]:
print(b)
b.shape

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


(3, 4)

In [23]:
print(c)
c.shape

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


(2, 2, 2)

In [24]:
# size : no of items in the array list
a.size

  

10

In [25]:
b.size

12

In [26]:
c.size

8

In [27]:
# itemsize : every item acupy the membery
a.itemsize  

4

In [28]:
b.itemsize

8

In [29]:
c.itemsize

4

In [30]:
# dtype: check the data type
a.dtype 

dtype('int32')

In [31]:
b.dtype

dtype('float64')

In [32]:
c.dtype

dtype('int32')

In [33]:
 ## changing datatype 

In [34]:
# astype : use change the datatype
b.astype(np.int32)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [35]:
## Array operations 

In [36]:
 # scalar operations
 # arithmetic
 
b*2 # b is a matrix and 2 is a scaller

array([[ 0.,  2.,  4.,  6.],
       [ 8., 10., 12., 14.],
       [16., 18., 20., 22.]])

In [37]:
b+2

array([[ 2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9.],
       [10., 11., 12., 13.]])

In [38]:
# relational operater
b>5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [39]:
a==5

array([False, False, False, False, False,  True, False, False, False,
       False])

In [40]:
# vector operator : use only  two  array 
a1=np.arange(12).reshape(3,4)
a2=np.arange(12).reshape(3,4)
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [41]:
# vector operator : use only  two  array  
# arithmaic
a1+a2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [42]:
a1**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [43]:
# Array function

In [44]:
a1=np.random.random((3,3))
a1=np.round(a1*100)
a1

array([[70.,  7.,  3.],
       [38., 51., 87.],
       [92., 64., 14.]])

In [45]:
# max() : max function find the max number
# axis: find the row and columns
# 0 -> columns 1 -> row
np.max(a1)

92.0

In [46]:
# min() : find the mean number
np.min(a1)

3.0

In [47]:
# sum() : sum all the number
np.sum(a1)

426.0

In [48]:
# prod() : the product function all the item multilipection value
np.prod(a1)

20430838794240.0

In [49]:
# axis= : axis find the row and column
# all function applikayble
# axis=0 find the row
# axis=1 find the column
# axis=None find all the values
# axis=-1 find the last column
# axis=-2 find the second last column
# axis=-3 find the third last column
np.max(a1,axis=1)

array([70., 87., 92.])

In [50]:
# statistal function


In [51]:
# mean() : find the mean value
np.mean(a1,axis=1)

array([26.66666667, 58.66666667, 56.66666667])

In [52]:
# median() : find the median value
np.median(a1,axis=1)

array([ 7., 51., 64.])

In [53]:
# str() : find the strnder div value 
np.std(a1,axis=1)

array([30.68477726, 20.72572208, 32.26280969])

In [54]:
# var(): variance
np.var(a1,axis=1)

array([ 941.55555556,  429.55555556, 1040.88888889])

In [55]:
# dot product : use the two array dot product
# ex:- first matris  columns: (3,4) and second matris:(4,3) multiple row
# output: (3,3)

a3=np.arange(12).reshape(3,4)
a4=np.arange(12).reshape(4,3)

np.dot(a3,a4)

array([[ 42,  48,  54],
       [114, 136, 158],
       [186, 224, 262]])

In [56]:
# log and exponents
np.log(a1)

array([[4.24849524, 1.94591015, 1.09861229],
       [3.63758616, 3.93182563, 4.46590812],
       [4.52178858, 4.15888308, 2.63905733]])

In [57]:
#  exponents
np.exp(a1)



array([[2.51543867e+30, 1.09663316e+03, 2.00855369e+01],
       [3.18559318e+16, 1.40934908e+22, 6.07603023e+37],
       [9.01762841e+39, 6.23514908e+27, 1.20260428e+06]])

In [58]:
# round(): use the float number convert into integers
np.round(np.random.random((2,3))*100)

array([[90., 67., 48.],
       [77., 66., 60.]])

In [59]:
# floor : ex:-floor(4.7)=4
np.floor(np.random.random((2,3)))


array([[0., 0., 0.],
       [0., 0., 0.]])

In [60]:
# ceil: ex:- ceil(4.1)=5

np.ceil(np.random.random((2,3)))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [61]:
# indexing #

# In NumPy, indexing refers to selecting elements from an array using their positions (indices). 
# It's similar to Python list indexing but more powerful and flexible.



In [62]:
a1=np.arange(10)
a2=np.arange(12).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

In [63]:
print(a1)
print(a1[9])
print(a1[-1])

[0 1 2 3 4 5 6 7 8 9]
9
9


In [64]:
print(a2)
print(a2[1,2])
print(a2[2,3])
print(a2[1,0])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
6
11
4


In [65]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [66]:
a2[0:2,1:3]

array([[1, 2],
       [5, 6]])

In [67]:
print(a3)
print(a3[1,0,1])
print(a3[0,1,0])
print(a3[0,0,0])
print(a3[1,1,0])

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
5
2
0
6


In [68]:
# slicing # multiple item fetch 
# use n-1 

In [69]:
print(a1)
print(a1[2:5]) 
print(a1[2:5:2])

[0 1 2 3 4 5 6 7 8 9]
[2 3 4]
[2 4]


In [70]:
print(a2)
print(a2[0:1,])
print(a2[0,:])
print(a2[:,2])
print(a2[1:,1:3])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0 1 2 3]]
[0 1 2 3]
[ 2  6 10]
[[ 5  6]
 [ 9 10]]


In [71]:
# (::) use the alternate column and row
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [72]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [73]:
a2[1::2,::3]

array([[4, 7]])

In [74]:
a2[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [75]:
a3=np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [76]:
# second matrix
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [77]:
# 1 and 3rd matrix
a3[0::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [78]:
# first matrix first 2nd row
a3[0,1:2]

array([[3, 4, 5]])

In [79]:
# iterating : means looping

In [80]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [82]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [83]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [84]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [85]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [86]:
# all item display 
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [87]:
# Reshaping function

In [88]:
# Transpose()
# row --> columns
# column --> rows

a2


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [89]:
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [90]:
# second syntax
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [91]:
# ravel() : multiple dimsional array convert to one dimesinal array
print(a2)
a2.ravel()

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [92]:
# reshape() : change the shape of array row and columns

In [93]:
 # stacking : means jodna

In [94]:
# horizontal stacking
a4=np.arange(12).reshape(3,4)
a5=np.arange(12,24).reshape(3,4)

In [95]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [96]:
# multiple  horizitonal stacking
np.hstack((a4,a5,a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11, 20, 21, 22, 23]])

In [97]:
# vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [98]:
# multiple vertial stacking
np.vstack((a4,a5,a4,a5))


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [99]:
# splitting : differnt stacking
# spilitting means part me cut krna


In [100]:
# horizontal splitting
print(a4)
np.hsplit(a4,2) # 2 means 2 part division

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [ ]:
np.hsplit(a4,4) # 4 means 4 part division
                # only equal part division


[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [104]:
# vertical splitting 
print(a5)
np.vsplit(a5,3)
 

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]